--- # USER MODULE EXAMPLE
- hosts: slaves
  user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Add the user called tstapache to the apache web client
      user: name=devops comment="test user" shell=/bin/bash groups=wheel append=yes

