--- # SERVICE MODULE EXAMPLE
- 
  name: webservers
  hosts: slaves
  user: root
  connection: ssh
  tasks:
  - name: Install Web Server
    action: yum name=httpd state=installed
  - name: Start the Web Server
    service: name=httpd state=started
  - name: Enable HTTPD After Reboot
    service: name=httpd enabled=yes

