---
- name: build
  hosts: localhost
  gather_facts: no
  tasks: 
     - name: create a bucket
       aws_s3:
          ec2_region: "{{ AWS_REGION }}"
          bucket: "myneswbucketfordevopsclass"
          mode: create
